#![allow(dead_code)]

use crate::config::{
    AccentColor, AccessibleTextSize, AudioOutputDevice, AudioStabilityMode, CloseBehavior,
    DeclarativeAction, EqPreset, InterfaceDensity, InterfaceLanguage, MissingDeviceBehavior,
    StartupScreen, SubtitleSize, TextScale, ThemeMode, TimeFormat, UpdateChannel, VolumeLevel,
};
use crate::library::Catalog;
use crate::ui::state::{
    ActiveTab, Album, Artist, Folder, Genre, PreferencesSection, PreferencesTab, SearchFilter,
    SortOption, ThemeCategory, Track,
};

#[derive(Debug, Clone, PartialEq)]
pub enum UiMessage {
    TabSelected(ActiveTab),
    SelectArtist(Artist),
    SelectAlbum(Album),
    SelectGenre(Genre),
    SelectFolder(Folder),
    SelectTrack(Track),
    SelectPlaylist(usize),
    Playback(PlaybackMessage),
    Search(SearchMessage),
    ToggleLogoMenu,
    WindowMinimize,
    WindowToggleMaximize,
    WindowClose,
    OpenPlaylist,
    ClosePlaylist,
    OpenQueue,
    CloseQueue,
    ShowLibrary,
    OpenPreferences,
    ClosePreferences,
    PreferencesTabSelected(PreferencesTab),
    SetThemeMode(ThemeMode),
    SetFollowSystemTheme(bool),
    SetAccentColor(AccentColor),
    SetAccentAuto(bool),
    SetTextScale(TextScale),
    SetInterfaceDensity(InterfaceDensity),
    SetTransparencyBlur(bool),
    SetUiAnimations(bool),
    SetAccessibilityLargeText(bool),
    SetAccessibilityHighContrast(bool),
    SetAccessibilityReduceMotion(bool),
    SetIncreaseContrast(bool),
    SetReduceTransparency(bool),
    SetAccessibleTextSize(AccessibleTextSize),
    SetReduceAnimations(bool),
    SetReduceTransitions(bool),
    SetSubtitlesEnabled(bool),
    SetSubtitleSize(SubtitleSize),
    SetHighlightKeyboardFocus(bool),
    SetAdvancedShortcuts(bool),
    SetDefaultPlaybackSpeed(u8),
    SetPauseOnFocusLoss(bool),
    SetDefaultVolume(u8),
    SetAudioOutputDevice(AudioOutputDevice),
    SetMissingDeviceBehavior(MissingDeviceBehavior),
    SetGaplessPlayback(bool),
    SetCrossfadeSeconds(u8),
    SetAutomixEnabled(bool),
    SetNormalizeVolume(bool),
    SetVolumeLevel(VolumeLevel),
    SetEqEnabled(bool),
    SetEqPreset(EqPreset),
    SetEqBandGain(usize, f32),
    ResetEq,
    SetAudioStabilityMode(AudioStabilityMode),
    ResetAudioEngine,
    SetAudioDebugLogs(bool),
    SetLaunchAtStartup(bool),
    SetRestoreLastSession(bool),
    SetOpenOn(StartupScreen),
    SetCloseBehavior(CloseBehavior),
    SetInterfaceLanguage(InterfaceLanguage),
    SetTimeFormat(TimeFormat),
    SetAutoCheckUpdates(bool),
    SetUpdateChannel(UpdateChannel),
    SetAutoInstallUpdates(bool),
    SetSendErrorReports(bool),
    SetSendUsageStats(bool),
    LibraryFolderChanged(String),
    PickLibraryFolder,
    LibraryFolderPicked(Option<String>),
    SetAutoScanOnLaunch(bool),
    CachePathChanged(String),
    ClearCache,
    ClearHistory,
    SetNotificationsEnabled(bool),
    SetNowPlayingNotifications(bool),
    SetHardwareAcceleration(bool),
    SetLimitCpuDuringPlayback(bool),
    OpenLogsFolder,
    ReindexLibrary,
    ResetPreferences,
    RequestDeclarativeAction(DeclarativeAction),
    ConfirmDeclarativeAction(DeclarativeAction),
    CancelDeclarativeAction,
    TogglePreferencesSection(PreferencesSection),
    ToggleThemeCategory(ThemeCategory),
    CloseMenu,
    PlaybackTick,
    StartInitialScan,
    ScanTick,
    LibraryScanCompleted(Result<Catalog, String>),
    NavigateLibrary(LibraryNavigation),
    ActivateSelection,
    PlaylistNameChanged(String),
    CreatePlaylist,
    RenamePlaylist,
    DeletePlaylist,
    MovePlaylistItemUp(usize),
    MovePlaylistItemDown(usize),
    RemovePlaylistItem(usize),
    AddSelectedTrackToPlaylist,
    ClearQueue,
    MoveQueueItemUp(usize),
    MoveQueueItemDown(usize),
    DismissAudioNotice,
    LoadMoreArtists,
    LoadMoreAlbums,
    LoadMoreTracks,
    LoadMoreGenres,
    LoadMoreFolders,
    AlbumGenreChanged(String),
    AlbumYearChanged(String),
    SaveAlbumMetadata,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlaybackMessage {
    TogglePlayPause,
    NextTrack,
    PreviousTrack,
    ToggleShuffle,
    CycleRepeat,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SearchMessage {
    QueryChanged(String),
    SortChanged(SortOption),
    ToggleFilter(SearchFilter),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LibraryNavigation {
    Up,
    Down,
    Left,
    Right,
    NextPanel,
    PreviousPanel,
}
